<?php
$t_language_text_section_content_array = array(
    'ai_optimizer_title' => 'AI Product Optimizer',
    'ai_optimizer_description' => 'Generiert SEO-optimierte Produkttexte mit KI',
    'ai_optimizer_button' => 'SEO-Texte mit KI generieren',
    'ai_optimizer_success' => 'Texte erfolgreich generiert!',
    'ai_optimizer_error' => 'Fehler bei der Generierung',
    'ai_optimizer_config_saved' => 'Konfiguration gespeichert',
    'ai_optimizer_api_key_label' => 'OpenAI API Key',
    'ai_optimizer_model_label' => 'OpenAI Modell',
    'ai_optimizer_backup_management' => 'Backups verwalten',
    'ai_optimizer_backup_list' => 'Gespeicherte Backups',
    'ai_optimizer_backup_restore' => 'Wiederherstellen',
    'ai_optimizer_backup_delete' => 'Löschen',
    'ai_optimizer_backup_date' => 'Speicherdatum',
    'ai_optimizer_backup_status' => 'Status',
    'ai_optimizer_backup_languages' => 'Sprachen',
    'ai_optimizer_backup_actions' => 'Aktionen',
    'ai_optimizer_backup_restored' => 'Wiederhergestellt',
    'ai_optimizer_backup_available' => 'Verfügbar',
    'ai_optimizer_backup_delete_confirm' => 'Möchten Sie dieses Backup wirklich löschen?',
    'ai_optimizer_backup_restore_confirm' => 'Möchten Sie dieses Backup wirklich wiederherstellen?',
    'ai_optimizer_backup_deleted' => 'Backup erfolgreich gelöscht',
    'ai_optimizer_backup_restored_success' => 'Backup erfolgreich wiederhergestellt'
);
